sourcegraph/deploy-sourcegraph-docker

deploy-frontend-internal.sh, deploy-frontend.sh
The raw endpoint downloads archives to the local disk. These files can be
large, as such we mount a volume to avoid exhausting the usually low container
disk space.
Part of https://github.com/sourcegraph/sourcegraph/issues/1913
=> frontend: Specify volume for CACHE_DIR

deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger-agent.sh, deploy-jaeger-cassandra.sh, deploy-jaeger-collector.sh, deploy-jaeger-query.sh, deploy-management-console.sh, deploy-pgsql.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh
Prior to this change services could scale up to the # of cores, which was inconsistent with our Kubernetes deployments which enforce this is not possible via the same underlying mechanism (Docker resource constraints). This meant that some services could scale to consume their entire workload quickly, at the detriment of other services.
After this change, we have proper resource constraints in place which ensures this does not occur and system stability is ensured over e.g. responding to one specific query ASAP by using 100% of all cores.
=> all: add proper resource constraints

deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-zoekt-indexserver.sh, deploy.sh, prometheus/prometheus_targets.yml, replicas.sh, teardown.sh
After this change, in order to deploy multiple `gitserver`, `searcher`, `symbols`, or `frontend` replicas you can simply modify the `replicas.sh` file and then run `./deploy.sh`.
Multiple frontend containers will be exposed on consecutive ports (3080, 3081, 3082, and so on.)
For an example of how a complete configuration for multiple replicas looks like, see https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/31/files
=> add support for specifying replica counts for cluster deployments

deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh
This includes the final changes we want to ship for zoekt in 3.7. It requires
frontend to also be on the latest version of 3.7 since we made a minor change
to the zoekt API.
Part of https://github.com/sourcegraph/sourcegraph/pull/5290
=> Update zoekt for 3.7 release

deploy-grafana.sh, deploy-prometheus.sh, prometheus/README.md, prometheus/docker_rules.yml
This PR cleans up some things around monitoring I observed from https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/39
- Handle upgrades so no manual intervention is needed (Prometheus v1 data is not compatible with v2).
- Add back the `docker.rules` which are needed for the "Containers" dashboard.
- Minor README/ whitespace cleanup.
Fixes sourcegraph/sourcegraph#5546
=> Cleanup some monitoring changes

README.md, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, deploy.sh, prometheus/prometheus_targets.yml, replicas.sh
Updated the scripts to support multiple zoekt replicas. Copied what was done for other services.
Test Plan: Untested! Please check this out, but I suspect it should just work. Note: we will need new versions of frontend and zoekt before this actually works. You may want to hold of deploying this until then?
Part of https://github.com/sourcegraph/sourcegraph/issues/5725
=> zoekt: Support multiple replicas

docker-compose/.env, docker-compose/README.md, docker-compose/docker-compose.yaml
Removes the need to bind mount to local directories. Potentially also removes
some permission errors encountered.
Fixes: https://github.com/sourcegraph/sourcegraph/issues/7829
Did this while experimenting for https://github.com/sourcegraph/sourcegraph/issues/7803
=> docker-compose: use docker volumes

deploy-redis-cache.sh, docker-compose/docker-compose.yaml
This reverts commit 02c695926587e1ce9c01481ba675abc45d309e8e and updates
the image to the latest version (roll-forward).
Related to https://github.com/sourcegraph/infrastructure/pull/1829
=> redis: Make redis-cache persistent again

caddy/builtins/http.Caddyfile, caddy/builtins/https.custom-cert.Caddyfile, caddy/builtins/https.lets-encrypt-prod.Caddyfile, caddy/builtins/https.lets-encrypt-staging.Caddyfile, caddy/builtins/https.lets-encrypt.Caddyfile, docker-compose/docker-compose.yaml
This PR switches the default reverse proxy from nginx over to [Caddy 2](https://caddyserver.com/). In addition, default configurations for exposing sourcegraph over HTTP, HTTPS with lets encrypt, and HTTP with custom certs are provided. 
Many of our users will need to modify the nginx configuration in order to expose Sourcegraph properly. However: 
1. Our nginx configuration is quite verbose. This:
- makes it quite difficult to see the configuration points that user is 
- makes the upgrading process more difficult since the user will need to solve these large merge conflicts on each update 
1. Since we switched to nginx, we have lost the ability to easily provision Lets Encrypt certs - which makes it harder for users to share their new Sourcegraph instance with the rest of their team …
=> docker-compose: use caddy instead of nginx

docker-compose/README.md
See https://github.com/sourcegraph/sourcegraph/pull/9134
=> docker-compose: remove experimental wording, better upgrading documentation

deploy-frontend-internal.sh, deploy-frontend.sh, docker-compose/docker-compose.yaml
We'll be phasing out LSIF_SERVER_URL for LSIF_API_SERVER_URL and can remove the old var once the tags are updated. See change in https://github.com/sourcegraph/sourcegraph/pull/9259.
=> Add LSIF_API_SERVER_URL envvar to replace LSIF_SERVER_URL

deploy-frontend-internal.sh, deploy-frontend.sh, docker-compose/docker-compose.yaml
for https://github.com/sourcegraph/sourcegraph/pull/10704 - adds `PROMETHEUS_SERVER_URL` to allow the frontend to query metrics.
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: https://github.com/sourcegraph/deploy-sourcegraph/pull/697
=> add prometheus server URL

deploy-cadvisor.sh, docker-compose/docker-compose.yaml
https://github.com/sourcegraph/deploy-sourcegraph/pull/707#discussion_r429430670
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: https://github.com/sourcegraph/deploy-sourcegraph/pull/707
=> pin cadvisor to sourcegraph mirror

deploy-frontend-internal.sh, deploy-frontend.sh, docker-compose/docker-compose.yaml
closes https://github.com/sourcegraph/sourcegraph/issues/10399
Verified this works on both docker, docker-compose deployment types:
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+.DeployType%28%29+-file:/*_test.go&patternType=literal - also doesn't look like any of the call points could cause issues with the new values
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: n/a, this is only for docker/docker-compose deployments
=> set DEPLOY_TYPE for pure-docker, docker-compose

deploy-grafana.sh, docker-compose/docker-compose.yaml
for https://github.com/sourcegraph/sourcegraph/pull/11483
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: I don't believe this is needed there, since the default value of `sourcegraph-frontend-internal` is meant for k8s?
=> declare SRC_FRONTEND_INTERNAL for grafana

grafana/datasources/datasources.yaml
depends on https://github.com/sourcegraph/sourcegraph/pull/11583
context: grafana 7 has built-in jaeger support
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: https://github.com/sourcegraph/deploy-sourcegraph/pull/767
=> grafana: add jaeger datasource

docker-compose/docker-compose.yaml
Increase interval and timeout of all services to be less strict.
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: https://github.com/sourcegraph/deploy-sourcegraph/pull/817
=> Increase minimum interval and timeout for all services

docker-compose/docker-compose.yaml
The double quotes meant this Caddy configuration:
```
reverse_proxy {$SRC_FRONTEND_ADDRESSES}
```
Expanded to:
```
reverse_proxy "sourcegraph-frontend-0:3080 sourcegraph-frontend-1:3080 sourcegraph-frontend-2:3080"
```
Instead of:
```
reverse_proxy sourcegraph-frontend-0:3080 sourcegraph-frontend-1:3080 sourcegraph-frontend-2:3080
```
Which led to Sourcegraph being unavailable entirely:
```
2020/08/14 00:03:05.971	INFO	using provided configuration	{"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
run: adapting config using caddyfile: parsing caddyfile tokens for 'reverse_proxy': /etc/caddy/Caddyfile:7 - Error during parsing: parsing upstream address: parse "undefined://sourcegraph-frontend-0:3080 sourcegraph-frontend-1:3080 sourcegraph-frontend-2:3080": invalid …
```
=> docker-compose: do not quote env var values

deploy.sh, test/pure-docker/Vagrantfile, test/pure-docker/smoke-test.sh
These fixes were needed to get the `3.18-customer-replica` (pure-docker) test branch passing.
These may also help https://github.com/sourcegraph/sourcegraph/issues/12996 but I haven't tested on the baremetal agents yet.
=> pure-docker test fixes

README.md, test/pure-docker/Vagrantfile, test/pure-docker/servers.yaml
I ran into a couple of issues when testing locally and ended up with this set of suggestions.
- Add more options to env-vars which can be easily added to .envrc locally
```
❯ cat .envrc
export VAGRANT_SSH_USER="foobar"
export VAGRANT_SSH_KEY="~/.ssh/google_compute_engine"
```
- Load all CI envs from files, so its not mixed. I was unsure about `machine_type` and `network` as they will likely not change
- Move user testing to our Auxiliary project
- Split base provisioning (left in the `Vagrantfile`) and test commands (in the `servers.yaml`)
- Set default ssh user to `ENV['USER']` which is what `gcloud beta compute ssh` uses and will probably match most users
=> Vagrant suggestions

.gitignore
Ignore dhall files for security reasons (see [security issue 8](https://github.com/sourcegraph/security-issues/issues/8))
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph/pull/1053) change:
=> Ignore dhall files

deploy-minio.sh, deploy.sh, docker-compose/docker-compose.yaml, teardown.sh, test/docker-compose/smoke-test.sh, test/pure-docker/smoke-test.sh, test/pure-docker/volume-config.sh
This adds a MinIO deployment. Part of https://github.com/sourcegraph/sourcegraph/issues/14825.
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: https://github.com/sourcegraph/deploy-sourcegraph/pull/1158
=> Add MinIO deployment

RELEASING.md
For the automation component + more details see https://github.com/sourcegraph/sourcegraph/pull/15521
Part of work that closes https://github.com/sourcegraph/sourcegraph/issues/15325
=> releasing: remove manual updates

RELEASING.md
This feature was added in https://github.com/sourcegraph/sourcegraph/pull/15743, closes https://github.com/sourcegraph/sourcegraph/issues/15323
=> releasing: tag is done by release tooling

.github/PULL_REQUEST_TEMPLATE.md, deploy-cadvisor.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, tools/update-docker-tags.sh
Unfortuantely, https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/173 broke the upgrade tool, which assumes all images have sums, or at least that's my hypothesis - this change makes the script work again:
```
tools/update-docker-tags.sh 3.22.0
```
Renovate opened a PR to re-pin these images (https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/174), but it doesn't do so for the `deploy-*.sh` scripts, so I went and fixed those by hand.
Also added checklist items to hopefully ensure we always have sums and tags. Followups:
* https://github.com/sourcegraph/sourcegraph/issues/15896
* https://github.com/sourcegraph/deploy-sourcegraph/pull/1348
=> pin images in deploy-* scripts

test/pure-docker/smoke-test.sh
Testing this I found there are actually 59 containers.
```
pure-docker-test: sourcegraph-frontend-2
pure-docker-test: sourcegraph-frontend-1
pure-docker-test: sourcegraph-frontend-0
pure-docker-test: sourcegraph-frontend-internal
pure-docker-test: zoekt-webserver-0
pure-docker-test: zoekt-indexserver-0
pure-docker-test: syntect-server
pure-docker-test: symbols-3
pure-docker-test: symbols-2
pure-docker-test: symbols-1
pure-docker-test: symbols-0
pure-docker-test: searcher-15
pure-docker-test: searcher-14
pure-docker-test: searcher-13
pure-docker-test: searcher-12
pure-docker-test: searcher-11
pure-docker-test: searcher-10
pure-docker-test: searcher-9
pure-docker-test: searcher-8
pure-docker-test: searcher-7
pure-docker-test: searcher-6
pure-docker-test: searcher-5
pure-docker-test: …
```
=> Increase expected containers to 59

deploy-cadvisor.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/docker-compose.yaml, docker-compose/pgsql-only-migrate.docker-compose.yaml
This pull request is part of the Sourcegraph 3.22.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.22.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/15023
cc @pecigonzalo
=> release: sourcegraph@3.22.0

test/pure-docker/volume-config.sh
fixes error `pure-docker-test: chown: cannot access 'lsif-server*'`
=> remove lsif volume

.buildkite/test.sh, test/Vagrantfile, test/docker-compose/smoke-test.sh, test/pure-docker/smoke-test.sh
repos are in detached head mode in buildkite. This leverages the BK environment variable to get the info we need to differentiate between a regular branch or customer replica to test appropriately
=> qa: fix branch logic for buildkite

test/docker-compose/smoke-test.sh
customer-replica branches don't have a different number of containers for compose deployments.
=> fix expect containers for branches

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/automerge.yml, go.mod, go.sum, renovate.json, tools/enforce-tags/main.go, tools/update-docker-tags.sh
Closes https://github.com/sourcegraph/sourcegraph/issues/15896 , mirrors https://github.com/sourcegraph/deploy-sourcegraph/pull/1382
=> tools: generate update-docker-tags args from sourcegraph/sourcegraph

deploy-cadvisor.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/docker-compose.yaml, docker-compose/pgsql-only-migrate.docker-compose.yaml
This pull request is part of the Sourcegraph 3.22.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.22.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/16531)
cc @uwedeportivo
=> release: sourcegraph@3.22.1

RELEASING.md
=> releasing: clarify manual action not required for some steps

RELEASING.md
For item fix https://github.com/sourcegraph/sourcegraph/issues/16207, notes steps that can be skipped because you can just check Buildkite
=> releasing: note steps that are done in buildkite

RELEASING.md, TESTING.md
Moves any manual testing advice into TESTING.md and update details of new scripts as well as an attempt to generally tidy up the release process. 
Fixes https://github.com/sourcegraph/sourcegraph/issues/16646
=> update release and testing guide to better reflect new process

RELEASING.md
Fixes the version numbers in the pure-docker release which I think were misleading
Removes duplicate compose smoke test instructions which are now in TESTING.md
Instructs the release captain to create to merge the publish branch into customer replica, thus the last step of releasing docker is to close the PR eg: #196  created by the release tool
=> update release guide

.buildkite/pipeline.yaml, test/Vagrantfile
Fixes: https://github.com/sourcegraph/sourcegraph/issues/17020
We found some `docker-test-*` images that were not being destroyed by
the `self-destroy`. This is because the images were missing the required
`scope` that allowes them to perofrm the destroy call.
This also updates the image to be in-sync with `sourcegraph/sourcegraph`
=> Add self-destroy permissions to tests

deploy-cadvisor.sh, docker-compose/docker-compose.yaml
closes https://github.com/sourcegraph/sourcegraph/issues/17072, see https://github.com/sourcegraph/sourcegraph/issues/17072#issuecomment-757460360
=> cadvisor: add commented support for macos

RELEASING.md
I believe this step is no longer used as we want `master` to remain `insiders`.
=> Remove unused steps

prometheus/prometheus_targets.yml
Fixes https://github.com/sourcegraph/sourcegraph/issues/16552 for docker compose, pure docker.
I'm not clear what the previous value achieved. No rewrite rules kicked in and the label value in a live environment is "node" for all the containers and services. Don't think that's too useful. I left a couple as "node" where I couldn't find k8s or single server counterparts.
=> prometheus job label

docker-compose/db-only-migrate.docker-compose.yaml, tools/migrate.sh, tools/migration_vars
A script to migrate Sourcegraph single server deployments to compose:
I chose editing the dump file for sql commands as the bash foo to escape quotes was awful. Happy to revisit this if someone disagrees but I feel as though I burnt too much time here before it occurred to me it'd just be easier do it this way. 
fixes https://github.com/sourcegraph/sourcegraph/issues/11600
=> migrate single server to compose

deploy-codeinsights-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy.sh, docker-compose/docker-compose.yaml, prometheus/prometheus_targets.yml, teardown.sh, test/smoke-test.sh, test/volume-config.sh
This PR adds the codeinsights-db deployment, which is a TimescaleDB time series database deployment used for recording Code Insights data.
I have test both deployments start up as expected.
Fixes https://github.com/sourcegraph/sourcegraph/issues/17225
=> add codeinsights-db deployment

deploy-codeinsights-db.sh, docker-compose/docker-compose.yaml
I failed to verify `/data` was the correct path (it is for our other Postgres images, but not for this TimescaleDB image), which means codeinsights-db data is not being retained currently. I noticed this because the DB was lost on sourcegraph.com (chart looks empty.)
The good news is that I am actively working on building historical data for insights, so this data loss doesn't really matter - it'll all be rebuilt later.
Fixes https://github.com/sourcegraph/sourcegraph/issues/18704
Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>
=> codeinsights-db: correct data volume path

deploy-codeinsights-db.sh, docker-compose/docker-compose.yaml
I previously thought `PGDATA=/var/lib/postgresql/data/pgdata` was the default,
but it is definitely not: `/var/lib/postgresql/data` is.
I removed this from `deploy-codeinsights-db.sh` for consistency with the Docker
Compose deployment, but this would have broken existing pure-docker deployments
because they were storing data in the `pgdata` subdirectory previously.
I have added this to Docker Compose deployments here, for consistency, although
it is not strictly required (Docker Compose volumes, unlike Kubernetes ones, do
not appear ot have a `lost+found` file in them and as such Postgres is happy to
use the root of the volume - whereas in Kubernetes deployments it will complain
the directory is not empty and fail to start.)
Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>
=> insights: set PGDATA=/var/lib/postgresql/data/pgdata

deploy-frontend-internal.sh, deploy.sh, docker-compose/docker-compose.yaml
This stops the frontend containers competing for a lock and erroring during the migrations. 
This ensures the internal pod comes up first, as other services start to talk to this before an user would start accessing the UI. In addition, if a customer wants to create multiple replicas of the frontend the start order and potential conflict between containers is still accounted for.
=> use healthcheck to fix db lock

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.26.3 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19840)
cc @ggilmore
=> release: sourcegraph@3.26.3

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.27.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20315)
@slimsag Pure docker is going to be skipped for this release. See https://github.com/sourcegraph/sourcegraph/issues/20329 and follow the chain from there. 
cc @ggilmore
=> release: sourcegraph@3.27.1

docker-compose/docker-compose.yaml
Sourcegraph-internal will fail once if the relevant dbs are not up. This results in the docker-compose deployment failing to start until `docker-compose up -d` is ran again.
Adds `depends_on` to sourcegraph-internal for the codeintel-db & pgsql db
Fixes https://github.com/sourcegraph/sourcegraph/issues/20326
=> Configure healthcheck for sourcegraph-internal

deploy-gitserver.sh
ensures each gitserver replica has a unique hostname that matches the container name
Fixes https://github.com/sourcegraph/customer/issues/318#issuecomment-833655421
=> ensure hostname matches container name

deploy-pgsql.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This PR updates images that use sourcegraph/postgres-12
[_Created by Sourcegraph batch change `andre/update-postgres12.6-base-images`._](https://k8s.sgdev.org/users/andre/batch-changes/update-postgres12.6-base-images)
=> Update sourcegraph/postgres-12.6 images to latest

docker-compose/docker-compose.yaml
Both redis-cache and redis-store  have `maxmemory 6gb` in their redis.conf: https://github.com/sourcegraph/infrastructure/blob/main/docker-images/redis-cache/redis.conf#L4 and https://github.com/sourcegraph/infrastructure/blob/3d83a92ce64650f46754e2ac55c3accfe84ab0d7/docker-images/redis-store/redis.conf#L4.  According to https://redis.io/topics/lru-cache#eviction-policies, redis will start evicting things from its cache once it hits that limit. However, because our _k8s pod_ memory limits are also set to 6 GB - k8s will kill the redis pods before they have a chance to perform that eviction process. 
Giving redis one more gigabyte to work with should give it enough room to do its cache eviction without being OOMKilled
=> bump memory limits for redis-[cache,store] to 7 GB

deploy-precise-code-intel-worker.sh, deploy-worker.sh, deploy.sh, docker-compose/docker-compose.yaml, prometheus/prometheus_targets.yml, teardown.sh, test/smoke-test.sh, test/volume-config.sh
This PR introduces a deployment for the new `worker` service. Currently this service replaces background jobs related to codeintel that used to occur in each frontend. Additional background services will make its way into this service. Part of sourcegraph/sourcegraph#21761.
Related changes:
- [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph/pull/3082)
- [deploy-sourcegraph-dot-com](https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/7786)
- [deploy-sourcegraph-dogfood-k8s-2](https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s-2/pull/1884)
=> Introduce worker service

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-worker.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.29.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.29.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/22397)
cc @daxmc99
=> release: sourcegraph@3.29.1

deploy-pgsql.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
=> Use postgres alpine images everywhere

docker-compose/docker-compose.yaml
This gives Postgres more time to gracefully shutdown
=> Add 'stop_grace_period to database services

deploy-caddy.sh, docker-compose/docker-compose.yaml
Updates Caddy image to caddy 2.0.0-alpine sha256:83d9aa7a5f1bbcc0fc1b4720c183a5ec53dae7dc5d9fa555daf3db345010e7f9
=> Update Caddy Image in docker-compose.yaml

docker-compose/docker-compose.yaml
Jaeger is not working on Docker Compose currently due to missing env var stated in https://github.com/sourcegraph/sourcegraph/issues/21677#issuecomment-889433798
This PR adds the missing env var SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json so that jaeger can work on Docker Compose instances properly.
=> Fix Jaeger Tracing in Docker Compose

prometheus/prometheus_targets.yml
Convenience and parity with k8s (would have been useful for https://github.com/sourcegraph/customer/issues/470 where I realized too late they were on Compose)
Without this the postgres dashboards are also super unhelpful on Compose, e.g. https://demo.sourcegraph.com/-/debug/grafana/d/postgres/postgres?orgId=1
=> prometheus: scrape pg, redis instances by default

.buildkite/pipeline.yaml
related to https://github.com/sourcegraph/infrastructure/pull/2939
Prevents accidental assignment to test agents
=> buildkite: explicitly target queue in CI

RELEASING.md, pure-docker/deploy-pgsql.sh
I realized that the reason the pgsql version for pure-docker releases never updated is that the initial batch change wasn't updating the version. The container image in master was never updated to the new name, so the update-tags script couldn't find it.
I also included a small usability change on the pure-docker update process, so we don't have to resolve merge conflicts. In the next stage, we visually inspect the diffs and revert any unnecessary changes so this should be safe.
=> Update default pgsql docker image for pure-docker, process changes

docker-compose/docker-compose.yaml
The zoekt-indexserver-0 deployment used to have cpus specified but it was removed in [this commit](https://github.com/sourcegraph/deploy-sourcegraph-docker/commit/6cf878cdbfd1ea298209f1d08ae39dbd88c8e101) in 2020. It seems like that was unintentional. Without this setting, Grafana dashboards that rely on cadvisor metrics aren't tracking cpu usage, since there is no specified limit:
I'm uncertain of the impact of this change on the performance of indexserver: without the cpu setting, it may have had unlimited cpu usage and could now be throttled in cases where 8 cpus is not sufficient. However, the GOMAXPROCS setting may have already been limiting this behavior, and the corrected monitoring will allow easier tracking.
=> Add cpus setting for zoekt-indexserver-0

renovate.json
Change the renovate configuration slightly to follow the pattern found in [deploy-sourcegraph](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph/-/blob/renovate.json).
Notably, images should only try to update once a week instead of constantly, and the PR's should try to automerge.
=> Update renovate configuration to match deploy-sourcegraph schedule

go.mod, go.sum
https://github.com/sourcegraph/update-docker-tags/releases/tag/v0.10.0
[_Created by Sourcegraph batch change `sourcegraph/bump-update-docker-tags-v0.10.0`._](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/bump-update-docker-tags-v0.10.0)
=> Bump sourcegraph/update-docker-tags to v0.10.0

test/smoke-test.sh
catch all errors on exit, rather than in the testing function. Ensures that errors are logged during any failure point during the script.
=> log all errors on exit

RELEASING.md
- Add notes to validate deploy-psql.sql. Remind me to not mess up `deploy-psql.sh` again.
- Add a new section to document process of patch release in light of the branch protection rule
=> Update `pure_docker` release process

docker-compose/docker-compose.yaml
Deploy `3.36.3` (comment out `migrator` and set `NEW_MIGRATION=false`)
> You should set `CR_USERNAME` and `CR_PASSWORD` env var to avoid rate limiting
```bash
./tools/update-docker-tags.sh 3.36.3
```
Set db to read only to simulate migration failure
```bash
docker-compose exec pgsql bash
ALTER DATABASE sg SET default_transaction_read_only = true;
```
Deploy the new insiders build with migrators
`migrator` and `sourcegraph-frontend-internal` are broken, but `frontend-0` is still accessible and healthy.
```
caddy                           caddy run --config /etc/ca ...   Up             2019/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
cadvisor                        /usr/bin/cadvisor -logtost ...   Restarting
codeinsights-db                 docker-entrypoint.sh postgres    Up …
```
=> tweak frontend healthcheck

docker-compose/docker-compose.yaml
Adjust the defaults on the migrator container to be consistent with https://github.com/sourcegraph/deploy-sourcegraph/pull/4095. These are still probably too generous, but it's closer!
Ran docker-compose locally and confirmed migrator still worked.
=> Reduce default resources on migrator container

docker-compose/docker-compose.yaml
The codeintel-db exporter was scraping metrics from pgsql instead of the codeintel-db database.
docker-compose up, confirmed exporter connected:
```
time="2022-03-08T21:33:17Z" level=info msg="Starting Server: :9187" source="postgres_exporter.go:1850"
time="2022-03-08T21:33:35Z" level=info msg="Established new database connection to \"codeintel-db:5432\"." source="postgres_exporter.go:983"
time="2022-03-08T21:33:35Z" level=info msg="Semantic Version Changed on \"codeintel-db:5432\": 0.0.0 -> 12.6.0" source="postgres_exporter.go:1552"
```
=> Update codeintel-db exporter to scrape codeintel-db

.buildkite/pipeline.yaml
Migrates some of the other trivial steps in this repo to stateless agents
The same jobs on deploy-sourcegraph are already running on stateless agents. Green checks on this PR are also a valid test.
=> use stateless agents on non qa tests

.buildkite/pipeline.yaml
This reverts commit 333bf6d358b1243e1f2e5b08cfd2276bb60750ab.
not required
=> Revert "use stateless agents on non qa tests (#784)"

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, go.mod, go.sum, pure-docker/deploy-pgsql.sh
Just fixing a missed image tag update.
=> Update 3.38 with correct images

.buildkite/hooks/pre-command
Fixes the following error, where there does not appear to be any code checked out in the `BUILDKITE_BUILD_CHECKOUT_PATH`
A green build on this PR
=> use bash source as run directory

docker-compose/db-only-migrate.docker-compose.yaml
Wondering if this very, very small change is more correct. There are technically now two services in this file, right? And they're both postgres? If the change is more correct, then I will also create the same change for our Kubernetes repo.
None. Though confidence gained from [Slack thread](https://sourcegraph.slack.com/archives/C02E4HE42BX/p1650918019969739), between myself and @kevinwojo .
=> Clarify db-only-migrate.docker-compose.yaml

RELEASING.md
Steps are confusing and often come too late (already committed and see something shouldn't be), and can't force-push to correct changes either.
n/a
---
Derived from my [retro notes for the 3.40 release](https://docs.google.com/document/d/1VHBqsWocffw9W8NRGhw4lLzyaoqgc1fiNdmTMMaVLxM/edit#).
=> docs: adjusting pure-docker release steps

caddy/builtins/http.Caddyfile, caddy/builtins/https.custom-cert.Caddyfile, caddy/builtins/https.lets-encrypt-prod.Caddyfile, caddy/builtins/https.lets-encrypt-staging.Caddyfile, caddy/builtins/https.trusted-proxies.Caddyfile, docker-compose/docker-compose.yaml
This patches CVE-2021-42377 and CVE-2020-28928.
* CI checks
* @kevinwojo: I created a GCP compute instance and installed SG with Caddy using HTTPS via LetsEncrypt. I then upgraded Caddy to this latest version. Aside from providing a notice to our customers regarding the new `trusted_proxies` setting, I think this is safe.
=> Upgrade caddy

prometheus/prometheus_targets.yml
This adds a scrape config for a new port exposed by the worker service that serves the collected executor metrics.
Will have to test it once https://github.com/sourcegraph/sourcegraph/pull/36969 landed, otherwise we'll revert.
=> executors: Add new worker prometheus scrape target

docker-compose/docker-compose.yaml, pure-docker/deploy-otel-collector.sh
Turns out this can be quite a heavy-duty service - it was recently bumped in S2 (https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/1171), so we make a more modest bump here.
CI Passes
=> otel-collector: bump resources

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, go.mod, go.sum
A recent change caused the `update-docker-tags.sh` script to only run on the `./pure-docker` subdirectory, but we also want to run it against the `./docker-compose` subdirectory. Will make a separate PR to update the script to run against both, but the is the result of running `go run ./tools/enforce-tags/ "4.0.0" ./docker-compose` manually.
I cherry-picked Coury's commit on `master` that updates the pinned version so we also update the otel images.
Manually verified that the tags in `docker-compose.yaml` are now populated correctly
=> Update tags for 4.0 release

tools/update-docker-tags.sh
It looks like this was changed in 6d8ecf323dfb7857 to only run on `./pure-docker` when that was moved to a subdirectory, but that causes the images tags in `./docker-compose` to no longer be updated by this script.
Ran this manually in https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/857
=> Update script to also run on ./docker-compose subdirectory

test/smoke-test.sh
Adding up the number of expected containers in `./pure-docker/deploy.sh` comes out to 60, which is what the tests are coming up with too. 
Tests already yielded this number.
=> Reduce container count for pure-docker tests

prometheus/prometheus.yml
After upgrading to 4.2, the alerts were missing in Prometheus.
This is the config in Prometheus. The root directory of [prometheus.yml](https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/prometheus/prometheus.yml) is now [`sg_prometheus_add_ons`](https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/docker-compose/docker-compose.yaml#L463), so there is no path to the rules in `/sg_config_prometheus/`
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/docker-images/prometheus/prometheus.sh?L7 
Adding the path to the rules in `/sg_config_prometheus` added `/sg_config_prometheus/` to the config and brought the alerts back. This is how it's configured in k8s too: 
https://github.com/sourcegraph/deploy-sourcegraph/blob/master/base/prometheus/prome …
=> Add relative path for rules in sg_config_prometheus

RELEASING.md, test/smoke-test.sh
Customer replica is moving to a new [repo](https://github.com/sourcegraph/deploy-sourcegraph-docker-customer-replica-1). This PR deprecates the release instructions for the old customer-replica branch. 
N/A
=> remove customer-replica references from this repo

pure-docker/deploy-caddy.sh
matching up the version update from https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/904
tested in https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/904
=> Caddy version update pt2

.github/workflows/update-tags.yml, .tool-versions
Update to 1.19.6 because it fixes a bunch of CVEs.
[_Created by Sourcegraph batch change `jhchabran/update-to-go-1.19.6`._](https://sourcegraph.sourcegraph.com/users/jhchabran/batch-changes/update-to-go-1.19.6)
Test Plan: CI
=> Update to Go 1.19.6

.tool-versions
Update to 1.19.8 because it fixes multiple vulnerabilities.
[_Created by Sourcegraph batch change `evict/update-to-go1.19.8`._](https://sourcegraph.sourcegraph.com/users/evict/batch-changes/update-to-go1.19.8)
CI
=> Update to Go 1.19.8

docker-compose/executors/executor.docker-compose.yaml
Addressing a bug observed when deploying the default executor docker-compose manifest
related slack thread: https://sourcegraph.slack.com/archives/C02MR5PPMKJ/p1683741238126119
- tested these changes on a v5.0.3 docker-compose Sourcegraph instance
=> updated scratch bind mount volume config for executor service

docker-compose/docker-compose.yaml
This commit bumps up Caddy and mitigates all the high and critically reported findings.
Caddy runs locally, proxies the requests successfully to frontend.
=> caddy: bump up caddy to 2.7.3

.github/workflows/pr-auditor.yml, .github/workflows/update-tags.yml
Update to actions/checkout@v3 to avoid deprecation warning
Created as part of batch change: [_Created by Sourcegraph batch change `sourcegraph-operator-dax/Upgrade_actions_checkout_v2-v3`._](https://sourcegraph.sourcegraph.com/users/sourcegraph-operator-dax/batch-changes/Upgrade_actions_checkout_v2-v3)
=> ci: update to actions/checkout@v3

docker-compose/docker-compose.yaml, pure-docker/deploy-caddy.sh
* Update version of Caddy used by pure-docker deployment to modern version
* Update version of Caddy used by docker-compose to latest release
* Caddy [not referenced](https://sourcegraph.sourcegraph.com/search?q=context:global+r:sourcegraph/deploy-sourcegraph$+caddy&patternType=standard&sm=0&groupBy=repo) in deploy-sourcegraph
* Caddy [not referenced](https://sourcegraph.sourcegraph.com/search?q=context:global+r:sourcegraph/deploy-sourcegraph-docker-customer-replica-1$+caddy&patternType=standard&sm=0&groupBy=repo) in this repo
=> Update Caddy version to 2.7.4

test/upgrade-test.go
This PR creates a small standalone script written in golang which takes ugrade type (multiversion or standard) and progresses through the general upgrade procedure validating the upgrade was successful between specified versions. 
Validation between versions checks for:
- database schema drift
- Change in the pgsql `versions` table
- Any `migration_logs` marked as failed in the `migration_logs` table
Ex: 
```
λ ~/deploy-sourcegraph-docker/test/ wg/test-upgrades* upgrade-test -h
NAME:
upgrade-test - Upgrade test is an upgrade smoke test for Sourcegraph's docker-compose deployment type.
USAGE:
upgrade-test [global options] command [command options] [arguments...]
COMMANDS:
standard, std      Runs a standard upgrade test. between specified versions
Example:
upgrade-test standard -vs …
```
=> migrator: upgrade types smoke test

docker-compose/docker-compose.yaml, prometheus/prometheus_targets.yml
cAdvisor is currently not exposing its metrics endpoint over the docker container network in our default `deploy-sourcegraph-docker` docker-compose configuration, resulting in broken container level monitoring & alerting for this deployment method. This PR accomplishes the following:
- Removes unused `--port=8080` parameter passed to [cadvisor entrypoint script](https://github.com/sourcegraph/sourcegraph/blob/main/docker-images/cadvisor/entrypoint.sh)
- Exposes the cAdvisor metrics endpoint on the docker container network on port 48080
- Updates the Prometheus target port for cAdvisor to 48080
Note: this brings `deploy-sourcegraph-docker` in line with [deploy-sourcegraph-helm](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/templates/cadvisor/cadvisor.Da …
=> Fix for prometheus scraping of cAdvisor metrics 

docker-compose/docker-compose.yaml, pure-docker/deploy-caddy.sh
Patches:
* CVE-2023-5363
* CVE-2023-45142
* CVE-2023-39325
* GHSA-m425-mq94-257g
- Tested locally with `./docker-compose/dev/run.sh up`
- Checked release notes for major changes
=> Update caddy to 2.7.6 to patch several vulns

.buildkite/hooks/pre-command, .buildkite/pipeline.yaml, .tool-versions, release.yaml
Adds a release manifest for use with rfc-795 release tooling
Closes https://github.com/sourcegraph/sourcegraph/issues/59062
Executed locally
=> rfc795: add release manifest

.buildkite/hooks/pre-command, .buildkite/pipeline.yaml, .tool-versions, README.md, release.yaml
Add the final layer of paint + QA (internal+promotion). 
I reworked how we handle branches, so we have the simplest and safest approach for the next few release cycles: 
- creating an internal release: 
- `<any branch>` -> `internal/release-vX.Y.Z` 
- opens a PR (ex: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/1019)
- CI build 
- once it reaches the finalization step in CI, it posts a message in the PR indicating that it's ready for promotion. 
- promoting a release:   
- `internal/release-vX.Y.Z` -> `promote/release-vX.Y.Z`
- opens a PR (ex: https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/1020) 
- CI build 
- once it reaches the finalization step in CI: 
- create a branch from `promote/release-vX.Y.Z` to `release-vX.Y.Z`
- it posts a message in the PR …
=> Update release manifest + QA 

release.yaml
Noticed we were using `{{tag}}` instead of `{{inputs.server.tag}}` which works as long as every internal release has the same version as the original sourcegraph one. 
This PR fixes that.
See https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/1022
=> fix(rel): use inputs.server.tag instead of tag

docker-compose/jaeger/docker-compose.yaml, otel-collector/config.yaml
- **fix(otel): update jaeger-all-in-one to support otel defaults**
- **docs(jaeger): add docs for more exposed ports**
- **fix(jaeger): fix image hash**
Related to [REL-166](https://linear.app/sourcegraph/issue/REL-166/cve-2024-36129-update-jaeger-and-otel-in-deploy-repos)
Manual Testing
=> fix(otel): Update Jaeger for OTEL changes

docker-compose/docker-compose.yaml, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-pgsql.sh
We need to use the new postgresql images
CI
=> fix: use postgresql 16 images

.github/workflows/semgrep.yml
Add Semgrep scan for scanning docker related config. Later include docker related ruleset to the rules repo.
- CI 🟢 
- CI for semgrep scan should scan actively for all pull request
=> chore: Add semgrep scan

docker-compose/docker-compose.yaml
Add `INDEXED_SEARCH_INDEXER` to sourcegraph-frontend-internal service ENVs. Follow up to https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/1208
CI
=> Add INDEXED_SEARCH_INDEXER to sourcegraph-frontend-internal service envs

batch-change/release.yaml
testing batch change automated release.yaml without git commands, since batch changes HAS TO handle that for us
testing through temporal + batch changes
=> feat: batch change flavour of release.yaml
