sourcegraph/deploy-sourcegraph-docker

deploy-syntect-server.sh
Fixes https://github.com/sourcegraph/sourcegraph/issues/2615
=> Bump syntect_server image

deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh
Setting GOGC=50, see https://github.com/sourcegraph/sourcegraph/issues/3792
=> update zoekt images

deploy-frontend-internal.sh, deploy-frontend.sh, deploy-grafana.sh
this is connected to
sourcegraph/sourcegraph#5543
this is how this looks like in the docker deploy context
=> frontend grafana dashboards in docker

deploy-grafana.sh, deploy-prometheus.sh
counterpart to
https://github.com/sourcegraph/sourcegraph/pull/5682
=> convert to semver for custom prom/graf docker images

deploy-prometheus.sh, metrics-and-tracing.md
Depends on a PR to fix https://github.com/sourcegraph/sourcegraph/issues/5843 first being merged and the image being updated in this repository.
=> document that fixing Prometheus disk permissions may be required on Linux hosts

deploy-lsif-server.sh
This updates the postgres config for lsif server after https://github.com/sourcegraph/sourcegraph/pull/5740.
=> Update lsif-server config with frontend addr

prometheus/prometheus_targets.yml
This is part of https://github.com/sourcegraph/sourcegraph/pull/6712
=> Add replacer to prometheus_targets.yml

deploy-syntect-server.sh
See also sourcegraph/sourcegraph#6843
Fixes sourcegraph/sourcegraph#6827
=> update syntect_server to include Starlark (Bazel) support

deploy-redis-cache.sh, deploy-redis-store.sh, docker-compose/docker-compose.yaml
This PR is a follow up to https://github.com/sourcegraph/sourcegraph/pull/8114
=> redis: update Redis images for persistence optimizations

deploy-syntect-server.sh, docker-compose/docker-compose.yaml
Ref. https://github.com/sourcegraph/sourcegraph/pull/8463
=> syntect_server: do not fail in environments without IPv6 support

docker-compose/docker-compose.yaml
Fixes https://github.com/sourcegraph/sourcegraph/issues/7780
=> docker-compose: add DEPLOY_TYPE=docker-compose to all relevant services

deploy-precise-code-intel-api-server.sh, deploy-precise-code-intel-bundle-manager.sh, deploy-precise-code-intel-worker.sh, docker-compose/docker-compose.yaml, prometheus/prometheus_targets.yml
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: https://github.com/sourcegraph/deploy-sourcegraph/pull/682
=> Update precise-code-intel service definitions

deploy-frontend-internal.sh, deploy-frontend.sh, deploy-jaeger.sh, docker-compose/docker-compose.yaml
Fixes https://github.com/sourcegraph/deploy-sourcegraph/pull/716
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change:https://github.com/sourcegraph/deploy-sourcegraph/pull/716
=> Add env var to frontend deployment for Jaeger

deploy-caddy.sh, deploy-pgsql.sh, deploy.sh, ensure-volume.sh, teardown.sh
Caddy was not being removed on teardown
=> Add caddy to teardown script

deploy-cadvisor.sh, docker-compose/docker-compose.yaml
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change: https://github.com/sourcegraph/deploy-sourcegraph/pull/722
=> cadvisor: apply args to reduce output

docker-compose/docker-compose.yaml
closes sourcegraph/sourcegraph#12220
=> fix key file name in example

deploy-cadvisor.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-pgsql.sh, deploy-precise-code-intel-bundle-manager.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/docker-compose.yaml, docker-compose/pgsql-only-migrate.docker-compose.yaml
created PR just to double-check (https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/RELEASING.md says push directly to master)
=> image tags: move to 3.19

deploy-cadvisor.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-pgsql.sh, deploy-precise-code-intel-bundle-manager.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/docker-compose.yaml, docker-compose/pgsql-only-migrate.docker-compose.yaml
upgrade docker image tags to 3.19.2
=> upgrade docker image tags to 3.19.2

docker-compose/README.md
change readme deploy instructions to 3.19.2
=> readme deploy instructions change to 3.19.2

deploy-cadvisor.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-pgsql.sh, deploy-precise-code-intel-bundle-manager.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/pgsql-only-migrate.docker-compose.yaml
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change:
=> update docker image tags to 3.20.0

deploy-cadvisor.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-pgsql.sh, deploy-precise-code-intel-bundle-manager.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/docker-compose.yaml, docker-compose/pgsql-only-migrate.docker-compose.yaml
Sister [deploy-sourcegraph](https://github.com/sourcegraph/deploy-sourcegraph) change:
=> upgrade to 3.20.1

test/Vagrantfile
Uses a pre built image to stop builds failing on apt-get errors
=> use prebuilt image

tools/update-docker-tags.sh
I'm going to automate this one day https://github.com/sourcegraph/sourcegraph/issues/15896
=> minio: version upgrades

deploy-cadvisor.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/docker-compose.yaml, docker-compose/pgsql-only-migrate.docker-compose.yaml
This pull request is part of the Sourcegraph 3.23.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.23.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/16108)
cc @uwedeportivo
=> release: sourcegraph@3.23.0

deploy-cadvisor.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/docker-compose.yaml, docker-compose/pgsql-only-migrate.docker-compose.yaml
This pull request is part of the Sourcegraph 3.24.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.24.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17144)
cc @davejrt
=> release: sourcegraph@3.24.0

deploy-cadvisor.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/docker-compose.yaml, docker-compose/pgsql-only-migrate.docker-compose.yaml
This pull request is part of the Sourcegraph 3.24.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.24.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17770)
cc @pecigonzalo
=> release: sourcegraph@3.24.1

docker-compose/db-only-migrate.docker-compose.yaml
adds the codeintel db for migration from sourcegraph server to compose
=> add codeintel-db

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.25.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/17727)
cc @davejrt
=> release: sourcegraph@3.25.0

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.25.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18609)
cc @pecigonzalo
=> release: sourcegraph@3.25.1

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.25.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.25.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18737)
cc @pecigonzalo
=> release: sourcegraph@3.25.2

deploy-frontend.sh, docker-compose/docker-compose.yaml
Still getting some failures, adjusting this for a little more leeway when bringing up frontend containers.
=> increase retries for frontend

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.26.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/18640)
cc @davejrt
=> release: sourcegraph@3.26.0

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.26.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.1)
* No tracking issue exists for this release
cc @daxmc99
=> release: sourcegraph@3.26.1

RELEASING.md, deploy-codeintel-db.sh, deploy-pgsql.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
=> Use Postgres 12

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.26.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.26.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19775)
cc @ggilmore
=> release: sourcegraph@3.26.2

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.27.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/19746)
cc @ggilmore
=> release: sourcegraph@3.27.0

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.27.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20377)
/RELEASING.md) to complete this PR (note: `pure-docker` release is optional for patch releases)
Skipping pure-docker for this release. 
cc @ggilmore
=> release: sourcegraph@3.27.2

.buildkite/pipeline.yaml
Built in https://github.com/sourcegraph/infrastructure/pull/2514/files
=> update gcp image

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.27.3 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20420)
cc @ggilmore
=> release: sourcegraph@3.27.3

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.27.4 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20452)
cc @davejrt
=> release: sourcegraph@3.27.4

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.27.5 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.27.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20948)
cc @davejrt
=> release: sourcegraph@3.27.5

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.28.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.28.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/20996)
cc @davejrt
=> release: sourcegraph@3.28.0

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-worker.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.29.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.29.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/21370)
cc @daxmc99
=> release: sourcegraph@3.29.0

.buildkite/pipeline.yaml
Uses image built from https://github.com/sourcegraph/infrastructure/pull/2649 with sudo access for the vagrant user
Aims to resolve https://github.com/sourcegraph/sourcegraph/issues/21594
=> update image used by vagrant

docker-compose/docker-compose.yaml
Fixes https://github.com/sourcegraph/sourcegraph/issues/21677
=> Upgrade Jaeger

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-worker.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, ensure-volume.sh, test/Vagrantfile
This pull request is part of the Sourcegraph 3.30.0 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.30.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/22300)
cc @daxmc99
=> release: sourcegraph@3.30.0

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-worker.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.30.1 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.30.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23143)
cc @daxmc99
=> release: sourcegraph@3.30.1

RELEASING.md
=> Postgres 12 is now required

docker-compose/README.md
into https://github.com/sourcegraph/sourcegraph/pull/23218  for https://github.com/sourcegraph/sourcegraph/issues/22427
=> docker-compose: migrate documentation out of repo

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-worker.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.30.2 release.
* [Release campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.30.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23304)
cc @davejrt
=> release: sourcegraph@3.30.2

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-worker.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.30.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch changes/release-sourcegraph-3.30.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23326)
cc @ggilmore
=> release: sourcegraph@3.30.3

deploy-cadvisor.sh, deploy-codeinsights-db.sh, deploy-codeintel-db.sh, deploy-frontend-internal.sh, deploy-frontend.sh, deploy-github-proxy.sh, deploy-gitserver.sh, deploy-grafana.sh, deploy-jaeger.sh, deploy-minio.sh, deploy-pgsql.sh, deploy-precise-code-intel-worker.sh, deploy-prometheus.sh, deploy-query-runner.sh, deploy-redis-cache.sh, deploy-redis-store.sh, deploy-repo-updater.sh, deploy-searcher.sh, deploy-symbols.sh, deploy-syntect-server.sh, deploy-worker.sh, deploy-zoekt-indexserver.sh, deploy-zoekt-webserver.sh, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
This pull request is part of the Sourcegraph 3.30.4 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.30.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/23996)
cc @ggilmore
=> release: sourcegraph@3.30.4

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-query-runner.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.31.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.31.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/24515)
cc @ggilmore
=> release: sourcegraph@3.31.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-query-runner.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.31.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.31.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/24737)
cc @davejrt
=> release: sourcegraph@3.31.2

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml
switches db's to alpine images.
=> update images, switch to alpine

docker-compose/docker-compose.yaml, pure-docker/deploy-pgsql.sh
Uses alpine-based Postgres image. This image will reindex the database on startup.
=> Use alpine image on 3.31

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-query-runner.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.32.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.32.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/25002)
cc @davejrt
=> release: sourcegraph@3.32.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-query-runner.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.32.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.32.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/27764)
=> release: sourcegraph@3.32.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-query-runner.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.33.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.33.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/27855)
=> release: sourcegraph@3.33.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-query-runner.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.34.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.34.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/26714)
=> release: sourcegraph@3.34.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-query-runner.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.33.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.33.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28044)
cc @kevinwojo
=> release: sourcegraph@3.33.2

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-query-runner.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.34.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.34.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28104)
cc @kevinwojo
=> release: sourcegraph@3.34.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-query-runner.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.34.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.34.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28640)
cc @kevinwojo
=> release: sourcegraph@3.34.2

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.35.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.35.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/28613)
cc @kevinwojo
=> release: sourcegraph@3.35.0

.tool-versions, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.35.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.35.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/29403)
cc @kevinwojo
=> release: sourcegraph@3.35.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.36.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/29290)
=> release: sourcegraph@3.36.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.36.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30041)
=> release: sourcegraph@3.36.1

.buildkite/ci-checkov.sh, .buildkite/pipeline.yaml, .tool-versions
This is the integration of the terraform scanner into this pipeline.
There should not be any terraform code here, but, in case that changes.
This is part of a task I was assigned to add Checkov to scan terraform code in all repositories that use buildkite.
Change for deploy-sourcegraph:https://github.com/sourcegraph/deploy-sourcegraph/pull/4057
If that matters as they may well end up being independent.
=> Added Checkov

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.36.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30200)
=> release: sourcegraph@3.36.2

.buildkite/ci-checkov.sh
Incorporated @bobheadxi's changes.
=> Updated script

.tool-versions
remove asdf install python and use system python to reduce run time in CI
[_Created by Sourcegraph batch change `dave/python`._](https://k8s.sgdev.org/users/dave/batch-changes/python)
=> use system python

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.36.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.36.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30562)
cc @michaellzc
=> release: sourcegraph@3.36.3

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
=> merge 3.35.2 (changes unrelated to upgrade)

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.35.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.35.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30637)
cc @michaellzc
=> release: sourcegraph@3.35.2

renovate.json
=> Fix formatting on renovate.json

.buildkite/ci-checkov.sh
=> Enabled checkov skiplist

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.37.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.37.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30051)
cc @coury-clark
=> release: sourcegraph@3.37.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.38.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.38.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/31768)
cc @camdencheek
=> release: sourcegraph@3.38.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
Merge 3.38.1 patch commits into 3.38 branch
N/A
=> 3.38.1 customer replica

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.38.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.38.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/33457)
cc @camdencheek
=> release: sourcegraph@3.38.1

prometheus/prometheus_targets.yml
Need to target the exporter container
=> Update prometheus_targets.yml for codeinsights-db

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.39.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.39.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/32836)
cc @keegancsmith
=> release: sourcegraph@3.39.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, prometheus/prometheus_targets.yml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
=> 3.39.1 customer replica fix fix

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.39.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.39.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34545)
cc @coury-clark
=> release: sourcegraph@3.39.1

.github/workflows/pr-auditor.yml, .github/workflows/update-tags.yml, .tool-versions
=> Upgrade golang version

docker-compose/docker-compose.yaml
See https://github.com/sourcegraph/deploy-sourcegraph/pull/4136
N/A
=> Make the Postgres healthchecks more lenient

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.40.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/36790)
cc @sashaostrikov
=> release: sourcegraph@3.40.2

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.41.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.41.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/37183)
cc @BolajiOlajide
=> release: sourcegraph@3.41.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.41.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.41.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38644)
cc @sashaostrikov
=> release: sourcegraph@3.41.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.42.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38119)
cc @mohammadualam
=> release: sourcegraph@3.42.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.43.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39333)
cc @coury-clark
=> release: sourcegraph@3.43.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-jaeger.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 3.43.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/41485)
cc @indradhanush
=> release: sourcegraph@3.43.2

pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.0.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.0.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/41759)
cc @camdencheek
=> release: sourcegraph@4.0.0

go.mod, go.sum
Part of https://github.com/sourcegraph/sourcegraph/issues/41949
Update pinned version to include otel images
N/A
=> update images pin

pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/42112)
cc @camdencheek
=> release: sourcegraph@4.0.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
I ran `sg ops update-images -kind compose -pin-tag 4.0.1 <each yaml>`
=> Fix image tags

pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh, test/smoke-test.sh, test/volume-config.sh
[Patch Release #43468](https://github.com/sourcegraph/sourcegraph/issues/43468)
=> upgrade to v4.1.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh, test/smoke-test.sh, test/volume-config.sh
This pull request is part of the Sourcegraph 4.1.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43468)
cc @BolajiOlajide
=> release: sourcegraph@4.1.1

pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
=> upgrade to v4.1.2

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.1.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43612)
cc @BolajiOlajide
=> release: sourcegraph@4.1.2

pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
=> upgrade to v4.1.3

otel-collector/config.yaml
update healthz extension config for otel 0.65
Part of:
- https://github.com/sourcegraph/sourcegraph/pull/44543
deploy locally and check otel collector comes up
=> otel: update otel config for 0.65

.tool-versions
Raises the go tool version to 1.19.3 to match src/src
N/A
=> go version 1.19.3

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-minio.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.2.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.2.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43423)
cc @coury-clark
=> release: sourcegraph@4.2.0

otel-collector/config.yaml, prometheus/prometheus_targets.yml
Part of:
- https://github.com/sourcegraph/sourcegraph/pull/45009
CI and run local
Metrics show up in pomotheus
=> otel: add metrics endpoint and scrape target

go.mod, go.sum
=> mod: update images list

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, go.mod, go.sum, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.3.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/45566)
cc @daxmc99
=> release: sourcegraph@4.3.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.4.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/45780)
cc @BolajiOlajide
=> release: sourcegraph@4.4.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.4.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/46931)
cc @mrnugget
=> release: sourcegraph@4.4.1

.github/PULL_REQUEST_TEMPLATE.md
Had to move this to a new branch because the branch name was triggering the wrong test set.
Just updates the PR template to reference the new customer replica repo.
N/A
=> update PR template for customer replica repo

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.4.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47256)
cc @mrnugget
=> release: sourcegraph@4.4.2

docker-compose/docker-compose.yaml
This will address [CVE-2022-34037](https://www.cve.org/CVERecord?id=CVE-2022-34037)
CI Checks
=> Caddy version update 

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.5.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47836)
=> release: sourcegraph@4.5.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 4.5.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48151)
=> release: sourcegraph@4.5.1

docker-compose/docker-compose.yaml
Updates sourcegraph-frontend-internal debug host to container name defined [here](https://github.com/sourcegraph/deploy-sourcegraph-docker/blob/master/docker-compose/docker-compose.yaml#L183)
Tested on https://cse-aws-test.sgdev.org/
=> Updates sourcegraph-frontend-internal debug host

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.0.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48131)
=> release: sourcegraph@5.0.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50405)
=> release: sourcegraph@5.0.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.0.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50811)
=> release: sourcegraph@5.0.2

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
Add ovverride file to enable Embeddings service
Tested locally, embeddings successfully generated and stored in blobstore
=> Embeddings Service

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.0.4 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52092)
=> release: sourcegraph@5.0.4

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.0.6 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/53491)
=> release: sourcegraph@5.0.6

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.1.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/49918)
=> release: sourcegraph@5.1.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.1.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54459)
=> release: sourcegraph@5.1.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.1.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54543)
=> release: sourcegraph@5.1.2

docker-compose/docker-compose.yaml
=> chore: delete left-over comment

docker-compose/executors/executor.docker-compose.yaml
This commit updates a url. Manually tested.
=> edit dead URL

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.1.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54899)
=> release: sourcegraph@5.1.3

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.1.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/55328)
=> release: sourcegraph@5.1.5

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.1.6 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/55718)
=> release: sourcegraph@5.1.6

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.1.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56213)
=> release: sourcegraph@5.1.7

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.1.8 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.8)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56395)
=> release: sourcegraph@5.1.8

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.1.9 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.9)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56794)
=> release: sourcegraph@5.1.9

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
Part of https://github.com/sourcegraph/sourcegraph/issues/56907
CI
=> release: sourcegraph@5.2.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.2.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/57319)
=> release: sourcegraph@5.2.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.2.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58049)
=> release: sourcegraph@5.2.2

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.2.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58310)
=> release: sourcegraph@5.2.3

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.2.4 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58662)
=> release: sourcegraph@5.2.4

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.2.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58967)
=> release: sourcegraph@5.2.5

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.2.6 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59481)
=> release: sourcegraph@5.2.6

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-github-proxy.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.2.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59830)
=> release: sourcegraph@5.2.7

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.3.0 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60032)
=> release: sourcegraph@5.3.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.3.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60691)
=> release: sourcegraph@5.3.1

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.3.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60972)
=> release: sourcegraph@5.3.2

.buildkite/pipeline.yaml, docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, release.yaml
=> (promote) release: build v5.3.666

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-blobstore.sh, pure-docker/deploy-cadvisor.sh, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-frontend-internal.sh, pure-docker/deploy-frontend.sh, pure-docker/deploy-gitserver.sh, pure-docker/deploy-grafana.sh, pure-docker/deploy-migrator.sh, pure-docker/deploy-node-exporter.sh, pure-docker/deploy-otel-collector.sh, pure-docker/deploy-pgsql.sh, pure-docker/deploy-precise-code-intel-worker.sh, pure-docker/deploy-prometheus.sh, pure-docker/deploy-redis-cache.sh, pure-docker/deploy-redis-store.sh, pure-docker/deploy-repo-updater.sh, pure-docker/deploy-searcher.sh, pure-docker/deploy-symbols.sh, pure-docker/deploy-syntect-server.sh, pure-docker/deploy-worker.sh, pure-docker/deploy-zoekt-indexserver.sh, pure-docker/deploy-zoekt-webserver.sh
This pull request is part of the Sourcegraph 5.3.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/61302)
=> release: sourcegraph@5.3.3

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/embeddings/embeddings.docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
Update image tags from `5.6.185` release in `master`.
Tested locally
=> release: cherrypick 5.6.185 release

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
=> (promote) release: build v5.7.0

.github/workflows/backport.yml
Standardizing across deploy-* repos
NA
=> feat/ci: Add backport GHA

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
=> Release update images

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
=> (promote) release: build v5.8.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
=> (internal) release_patch: build v5.8.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
=> update tags for 5.8.1579

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
=> (promote) release: build v5.9.1590

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, pure-docker/deploy-codeinsights-db.sh, pure-docker/deploy-codeintel-db.sh, pure-docker/deploy-pgsql.sh
=> (promote) release: build v5.10.0

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
=> (promote) release: build v5.10.2832

docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml, otel-collector/config.yaml
=> (promote) release: build v5.11.3601

docker-compose/db-only-migrate.docker-compose.yaml, docker-compose/docker-compose.yaml, docker-compose/executors/executor.docker-compose.yaml, docker-compose/jaeger/docker-compose.yaml
=> (promote) release: build v6.3.4167
